AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-sample-aws-sam

# 独自定義。ESBuildを使ってビルドするための共通設定。
Metadata: &EsbuildSharedMetadata
  BuildMethod: esbuild
  BuildProperties: &EsbuildSharedBuildProperties
    Format: esm
    Minify: false
    Target: es2022
    OutExtension:
      - .js=.mjs
    Sourcemap: true

Parameters:
  Env:
    Type: String
    AllowedValues:
      - prd
      - stg
    Description: Environment name
  Hoge:
    Type: String
    Description: Hoge

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Environment:
      Variables:
        ENV: !Ref Env
  Api:
    # Stageの生成を無効化するために設定、OpenAPIは使用していない: https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-openapiversion
    OpenApiVersion: 3.0.2

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: hello-world.handler
      Environment:
        Variables:
          HOGE: !Ref Hoge
          FUGA: fuga
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/hello
            Method: get
    Metadata:
      <<: *EsbuildSharedMetadata
      BuildProperties:
        <<: *EsbuildSharedBuildProperties
        EntryPoints:
          - ./src/api/v1/hello-world.ts

  ScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: hello-world.handler
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
    Metadata:
      <<: *EsbuildSharedMetadata
      BuildProperties:
        <<: *EsbuildSharedBuildProperties
        EntryPoints:
          - ./src/schedule/hello-world.ts
